plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'smoke/sample_app/**/*'
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false
