name: Test Sentinel Analysis

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  test_sentinel:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1
        bundler-cache: true
    
    - name: Set up database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
    
    - name: Run tests with coverage
      run: bundle exec rspec
    
    - name: Run Test Sentinel analysis
      run: bundle exec test-sentinel generate --top-n 10
    
    - name: Upload analysis results
      uses: actions/upload-artifact@v4
      with:
        name: test-sentinel-analysis
        path: test_sentinel_analysis.json